version: '3'

services:
#   front:
#     image: node:15.2.0-alpine3.12
#     ports:
#       - "8000:8000"
#     volumes:
#       - ../front:/app
#     tty: true
  todo:
    image: hayd/alpine-deno
    ports:
      - "2020:2020"
    volumes:
      - ../todo:/app
    depends_on:
      - mongo
    working_dir: /app
    entrypoint:
      - deno
      - run
      - --allow-net
      - --allow-write
      - --allow-read
      - --allow-plugin
      - --allow-env
      - --unstable
      - server/server.ts
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
